onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/g_interface_mode
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/g_address_granularity
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/g_num_interrupts
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/clk_sys_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/rst_n_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_adr_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_dat_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_dat_o
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_cyc_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_sel_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_stb_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_we_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_ack_o
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_stall_o
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/irqs_i
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/irq_master_o
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/irqs_i_reg
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ctl_enable
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ctl_pol
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ctl_emu_edge
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ctl_emu_len
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_risr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ier
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ier_wr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_idr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_idr_wr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_imr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_var
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_eoir
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_eoir_wr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ivt_ram_addr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ivt_ram_data
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_ivt_ram_rd
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_swir
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/vic_swir_wr
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/got_irq
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/swi_mask
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/current_irq
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/irq_id_encoded
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/state
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_in
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/wb_out
add wave -noupdate /main/DUT/U_VIC/U_Wrapped_VIC/timeout_count
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {19332000000 fs} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {18085113600 fs} {19397625600 fs}
